### ISSUE TITLE
Creating a Github page to illustrate the veganburger

### ISSUE THREAD

**Issue by thomasneil** [duanewilson/veganburger#1]
This is a great, well thought out, well designed solution for a more clearly visible burgermenu. I hope more people use it.

To that end, would it be ok for me to replicate the current veganburger neocities website, and put it up as a github page on this repository?

**Comment by duanewilson** [comment]
🥰

That’s likely a better home for it. TY

**Comment by thomasneil** [comment]
Hi Duane, I've made a pull request here
https://github.com/duanewilson/veganburger/pull/2

I've been able to replicate your site code and put it on github. A test is here at https://thomasneil.github.io/veganburger/
You'll be able to serve the site via github pages.

P.S. I'm pretty worried about putting my phone number up on a public site like this, I don't know if you should risk it

**Comment by duanewilson** [comment]
Edited. Thanks for pointing it out!
